
# Starts the DB, the API and the UI
version: '3'

services:

  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=rag_user
      - POSTGRES_USER=rag_password
      - POSTGRES_PASSWORD=rag_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # api:
  #   hostname: 127.0.0.1
  #   dockerfile: apps.my_sample_api.Dockerfile
  #   build:
  #     context: .
  #     target: api
  #   ports:
  #     - 8000:8000
  #   depends_on: 
  #     - db
  #   environment:
  #     - VECTOR_STORE_TYPE=pgvector
  #     - CONNECTION_STRING=postgresql://rag_user:ChangeMe@db:5432/api
